name: Publish Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          # 设置 npm registry 为默认的 npmjs.org
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Publish package
        run: npm publish --access public
        env:
          # 请确保在仓库 Secrets 中配置了 NPM_TOKEN
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
