name: Publish Package

on:
  push:
    branches:
      - main  # 或者你所使用的发布分支
    # 如果希望只针对打 tag 时发布，可以用下面的触发条件：
    # tags:
    #   - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'  # 使用 GitHub Packages 的 registry

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}
